name: Weather Scraper

on:
  push
#  schedule:
#    - cron: "*/5 * * * *"
#  workflow_dispatch:

concurrency:
  group: weather-scraper
  cancel-in-progress: true


jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python deps
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browser
        run: |
          python -m playwright install chromium

      - name: Create data-dir
        run: |
          mkdir data

      - name: Run scraper
        env:
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
          INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
        run: |
          python get_json.py
